"use strict";
exports.__esModule = true;
exports.HUNDRED = 100;
exports.THOUSAND = 1000;
exports.MILLION = 1000000;
exports.BILLION = 1000000000;
exports.MINUTE_S = 60;
exports.HOUR_S = exports.MINUTE_S * 60;
exports.DAY_S = exports.HOUR_S * 24;
exports.MINUTE_MS = exports.MINUTE_S * exports.THOUSAND;
exports.HOUR_MS = exports.HOUR_S * exports.THOUSAND;
exports.DAY_MS = exports.DAY_S * exports.THOUSAND;
